{
  assertValid();
  try {
    gitOperation(new GitOperation<Object>(){
      public Object call(      Git git,      GitContext context) throws Exception {
        context.requirePush();
        return null;
      }
    }
,false);
  }
 catch (  Exception e) {
    LOG.warn("Failed to perform a pull " + e,e);
  }
}
